version: "3"
services:
  mariadb:
    image: mariadb:11.3.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: livestreaming
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
    restart: always