import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { ReactNode } from 'react';
import Head from 'next/head';

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <style>{`body { margin: 0;}`}</style>
        </Head>
        <div className="flex flex-col min-h-screen bg-gray-100">
          <header className="bg-red-600 text-white p-4 shadow-md">
            <h1 className="text-lg">YouTube-like Header</h1>
          </header>
          <div className="flex-grow">
            <main className="container mx-auto mt-4">
              {children}
            </main>
          </div>
          <footer className="bg-gray-200 text-center p-4 text-sm">
            Footer Content &copy; {new Date().getFullYear()}
          </footer>
        </div>
      </>
  );
}