import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { ReactNode } from 'react';
import Head from 'next/head';
import AuthSession from "@/app/_component/AuthSession";

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <AuthSession>
          {children}
      </AuthSession>
      </body>
      </html>
  );
}